# Generated by Django 4.1.7 on 2023-02-25 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=200, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('subscription_is_active', models.BooleanField(verbose_name='Подписка активна')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время отправки сообщения')),
                ('message_sender', models.CharField(max_length=200, verbose_name='Отправитель сообщения (ID)')),
                ('message_receiver', models.CharField(max_length=200, verbose_name='Получатель сообщения (ID)')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_is_read', models.BooleanField(verbose_name='Сообщение прочитано')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=200, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('subscription_is_active', models.BooleanField(verbose_name='Подписка активна')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время формирования заявки ')),
                ('name', models.CharField(max_length=200, verbose_name='Задача')),
                ('problem', models.TextField(verbose_name='Описание задачи')),
                ('exec_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (в часах)')),
                ('order_is_done', models.BooleanField(verbose_name='Заявка выполнена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbase.client', verbose_name='Клиент')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderbase.maker', verbose_name='Исполнитель')),
            ],
        ),
    ]
