# Generated by Django 4.1.7 on 2023-02-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='telegram_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID'),
        ),
    ]
