# Generated by Django 4.1.7 on 2023-02-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbase', '0002_alter_client_telegram_id_alter_maker_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderbase.order', verbose_name='Заказ'),
        ),
    ]
